/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute, createRootRoute, createRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as indexRoute } from './routes/index'

// Create Virtual Routes

const runsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/runs',
})

const schedulesRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/schedules',
})

const environmentsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/environments',
})

const analyticsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/analytics',
})

const webhooksRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/webhooks',
})

const integrationsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/integrations',
})

const systemRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/system',
})

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  indexRoute,
  runsRoute,
  schedulesRoute,
  environmentsRoute,
  analyticsRoute,
  webhooksRoute,
  integrationsRoute,
  systemRoute,
])

/* prettier-ignore-end */